artifact_uri: file:///workspaces/neural-networks-fundamentals/.laborantum/mlflow_logs/761117637739947366/d31ca127a50347948447ccf7d11e4e35/artifacts
end_time: 1782930688714
entry_point_name: ''
experiment_id: '761117637739947366'
lifecycle_stage: active
run_id: d31ca127a50347948447ccf7d11e4e35
run_name: autoencoder_training
source_name: ''
source_type: 4
source_version: ''
start_time: 1782930669285
status: 3
tags: []
user_id: root
