artifact_uri: file:///workspaces/neural-networks-fundamentals/.laborantum/mlflow_logs/761117637739947366/ea68d074314f41609a86d121ccb1f1d0/artifacts
end_time: 1782931451888
entry_point_name: ''
experiment_id: '761117637739947366'
lifecycle_stage: active
run_id: ea68d074314f41609a86d121ccb1f1d0
run_name: one_layer_fcnn_test_run
source_name: ''
source_type: 4
source_version: ''
start_time: 1782931418769
status: 3
tags: []
user_id: root
